language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods xcpretty slather --no-ri --no-rdoc
  - pod install --project-directory=KitchenSink

script:
  - set -o pipefail && xcodebuild test -workspace KitchenSink/MMDrawerControllerKitchenSink.xcworkspace -scheme MMDrawerControllerKitchenSink -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

after_success: slather
